### ISSUE TITLE
Add general items and classes

### ISSUE THREAD

**Issue by ghostrider-05** [ghostrider-05/kismet.code#4]
As mentioned in #1 some default classes should be added:
- [x] default actions and events from a clean install of UDK (accessible as `UDK.actions.default`, `UDK.events.default`, ...etc or `UDK.default<Items>.actions`)
- [x] kismet variables and utils for types such as random float / integer and object lists
- [x] input validation for items 

This would allow for quickly starting and only running other scripts when a local copy of the UDK setup preferred. If no scripts are installed the default items could also be used as fallback

Default classes:

**Variables**
- [x] Boolean
- [x] String
- [x] Vector
- [x] Object
- [x] Object list
- [x] Object volume
- [x] Named variables
- [x] External variables
- [x] Float
- [x] Integer
- [x] Player
- [x] Matinee data

**Other**
- [x] Color
- [x] Comments
- [x] Comment frames
